const API_URL='https://arabicapptest.roy-rachamim.workers.dev';
const GOOGLE_CLIENT_ID='174097869132-96j8tu8po9hot556h35d92267gb52mc2.apps.googleusercontent.com';
const STORAGE_KEY='shway-shway-session-progress-v1';
const USER_CODE_KEY='arabic-app-user-code-v1';
const GOOGLE_SESSION_KEY='arabic-app-google-session-v1';
const GOOGLE_PROFILE_KEY='arabic-app-google-profile-v1';
const VOCABULARY_CACHE_KEY='shway-shway-vocabulary-v1';
const LEGACY_KEYS=['shway-shway-progress-v2','shway-shway-progress-v1'];
let lessons=[],items=[],order=[],index=0,furthestIndex=0,sessionNumber=0,sessionResults={},progress={},shuffleOn=true,transitioning=false,activeView='home',listReturnView='home',featuredIndex=null,featuredTransitioning=false,featurePointerStart=null,wordPointerStart=null,drawerPointerStart=null,selectedLesson='all',sessionLesson='all',activeListType='all',sessionFilter='all',pageTransitioning=false,drawerCloseTimer=null,menuScrollY=0;
let userCode='',cloudSaveTimer=null,cloudSavePending=false;
let googleSession='',googleProfile=null;
let activeAudio=null,activeAudioButton=null,audioPauseTimer=null,audioRun=0;
const by=id=>document.getElementById(id);
const form=by('form'),feedback=by('feedback');
const AUDIO_ICON='<img alt="" src="upload/image(43).png">';
const PAUSE_ICON='<img alt="" src="upload/image(44).png">';
function restoreAudioIcon(button){if(button)button.innerHTML=AUDIO_ICON}
function showPauseIcon(button){if(button)button.innerHTML=PAUSE_ICON}

function itemKey(q){return q.id||q.w}
function stopAudio(){audioRun++;if(audioPauseTimer){clearTimeout(audioPauseTimer);audioPauseTimer=null}if(activeAudio){activeAudio.pause();activeAudio.currentTime=0}if(activeAudioButton){activeAudioButton.classList.remove('is-playing');restoreAudioIcon(activeAudioButton)}activeAudio=null;activeAudioButton=null}
function audioPath(q,type){return 'audio/'+encodeURIComponent(itemKey(q))+'-'+type+'.mp3'}
function playOneFile(q,type,run){return new Promise((resolve,reject)=>{if(run!==audioRun)return reject(new Error('stopped'));const audio=new Audio(audioPath(q,type));activeAudio=audio;audio.addEventListener('ended',()=>resolve(),{once:true});audio.addEventListener('error',()=>reject(new Error('missing '+type)),{once:true});audio.play().catch(reject)})}
async function playWordAndSentence(q,button){if(!q||!button||button.disabled)return;if(activeAudioButton===button){stopAudio();return}stopAudio();const run=audioRun;activeAudioButton=button;button.classList.remove('is-error');button.classList.add('is-playing');showPauseIcon(button);try{await playOneFile(q,'word',run);if(run!==audioRun)return;await new Promise(resolve=>{audioPauseTimer=setTimeout(resolve,300)});audioPauseTimer=null;if(run!==audioRun)return;if(q.s)await playOneFile(q,'sentence',run);if(run===audioRun)stopAudio()}catch(error){if(run!==audioRun)return;stopAudio();button.classList.add('is-error');button.title='חסר קובץ אודיו למילה או למשפט';setTimeout(()=>{button.classList.remove('is-error');restoreAudioIcon(button);button.title='השמעת המילה והמשפט'},1800)}}
function setAudioButton(q,prefix){const button=by(prefix+'Audio');if(button){restoreAudioIcon(button);button.disabled=!q?.id;button.dataset.itemId=itemKey(q)}}
function metaValues(value){return String(value||'').split('·').map(v=>v.trim()).filter(Boolean)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderMetaTags(element,value){element.innerHTML=metaValues(value).map(v=>'<button class="meta-tag" type="button" data-tag="'+escapeHtml(v)+'" aria-label="הצגת כל המילים עם הטאג '+escapeHtml(v)+'">'+escapeHtml(v)+'</button>').join('')}
function metaTagsHtml(value){return '<div class="meta-tags">'+metaValues(value).map(v=>'<button class="meta-tag" type="button" data-tag="'+escapeHtml(v)+'" aria-label="הצגת כל המילים עם הטאג '+escapeHtml(v)+'">'+escapeHtml(v)+'</button>').join('')+'</div>'}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function normalizeHebrew(value){return String(value||'').normalize('NFKD').replace(/[\u0591-\u05C7]/g,'').replace(/["'׳״.,!?;:()\-]/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
function matchesLocally(answer,meanings){const normalized=normalizeHebrew(answer);return meanings.some(m=>normalizeHebrew(m)===normalized)}
function grammar(type,binyan){const t=(type||'').trim().toLowerCase(),b=(binyan||'').trim();if(t==='verb')return 'פועל'+(b?' · בניין '+b:'');if(t==='noun')return 'שם עצם';if(t==='adj')return 'שם תואר';if(t==='expression')return 'ביטוי';if(t==='masdar')return 'מצדר'+(b?' · בניין '+b:'');return [type,b&&'בניין '+b].filter(Boolean).join(' · ')||'ללא סיווג'}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows}
function rowsToItems(rows,lesson){if(rows.length<2)return[];const h=rows[0].map(v=>v.trim().toLowerCase()),col=n=>h.indexOf(n.toLowerCase());return rows.slice(1).map((r,i)=>{const active=col('Active')<0?'TRUE':String(r[col('Active')]||'').trim().toUpperCase();return{id:r[col('ID')]||lesson.sheet+'_'+(i+1),lesson:lesson.sheet,w:(r[col('Arabic')]||'').trim(),m:(r[col('Hebrew')]||'').split(/\s*\/\s*/).filter(Boolean),tr:(r[col('Transliteration')]||'').trim(),f:grammar(r[col('Type')],r[col('Binyan')]),s:col('Example')<0?'':(r[col('Example')]||'').trim(),t:col('Example Hebrew')<0?'':(r[col('Example Hebrew')]||'').trim(),active:!['FALSE','0','NO'].includes(active)}}).filter(q=>q.w&&q.m.length&&q.active)}
function rowsToLessons(rows){if(rows.length<2)return[];const h=rows[0].map(v=>v.trim().toLowerCase()),col=n=>h.indexOf(n.toLowerCase());return rows.slice(1).map(r=>({sheet:String(r[col('Sheet')]||'').trim(),title:String(r[col('Title')]||'').trim(),source:String(r[col('Source')]||'').trim(),active:!['FALSE','0','NO'].includes(String(r[col('Active')]||'').trim().toUpperCase()),order:Number(r[col('Order')])||999})).filter(l=>l.sheet&&l.title&&l.active).sort((a,b)=>a.order-b.order)}
async function loadVocabulary(){try{const lessonResponse=await fetch(`${API_URL}?action=lessons`,{cache:'no-store'});if(!lessonResponse.ok)throw new Error('Lessons API '+lessonResponse.status);lessons=rowsToLessons(parseCsv(await lessonResponse.text()));const groups=await Promise.all(lessons.map(async lesson=>{const response=await fetch(`${API_URL}?action=vocabulary&sheet=${encodeURIComponent(lesson.sheet)}`,{cache:'no-store'});if(!response.ok)throw new Error('Vocabulary API '+response.status);return rowsToItems(parseCsv(await response.text()),lesson)}));items=groups.flat();if(!lessons.length||!items.length)throw new Error('לא נמצאו שיעורים פעילים');localStorage.setItem(VOCABULARY_CACHE_KEY,JSON.stringify({lessons,items,savedAt:new Date().toISOString()}));return{cached:false}}catch(error){let cached=null;try{cached=JSON.parse(localStorage.getItem(VOCABULARY_CACHE_KEY)||'null')}catch{}if(!cached?.lessons?.length||!cached?.items?.length)throw error;lessons=cached.lessons;items=cached.items;return{cached:true}}}
async function api(body){const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'שגיאה בחיבור ל-AI');return data}

function makeUserCode(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return [...bytes].map(value=>value.toString(16).padStart(2,'0')).join('')}
function getUserCode(){let code=(localStorage.getItem(USER_CODE_KEY)||'').trim().toLowerCase();if(!/^[a-f0-9]{32}$/.test(code)){code=makeUserCode();localStorage.setItem(USER_CODE_KEY,code)}return code}
function setCloudStatus(text,error=false){const el=by('cloudStatus');if(!el)return;el.textContent=text;el.classList.toggle('error',error)}
function statePayload(){return{version:4,sessionNumber,progress,current:{ids:order.map(itemKey),index,furthestIndex,results:sessionResults,lesson:sessionLesson,filter:sessionFilter},selectedLesson,shuffleOn,savedAt:new Date().toISOString()}}
function applySavedState(saved){if(!saved||typeof saved!=='object')return;sessionNumber=saved.sessionNumber||0;progress=saved.progress||{};shuffleOn=saved.shuffleOn!==false;selectedLesson=saved.selectedLesson||'all';sessionLesson=saved.current?.lesson||'all';sessionFilter=saved.current?.filter||'all';const ids=saved.current?.ids||[];order=ids.map(id=>items.find(q=>itemKey(q)===id)).filter(Boolean);index=Math.min(saved.current?.index||0,Math.max(0,order.length-1));furthestIndex=Math.min(Math.max(index,saved.current?.furthestIndex??index),Math.max(0,order.length-1));sessionResults=saved.current?.results||{}}
function mergeWordProgress(first,second){if(!first)return second;if(!second)return first;const a=Date.parse(first.updatedAt||'')||0,b=Date.parse(second.updatedAt||'')||0;if(a||b)return b>a?second:first;if(first.status==='retry'||second.status==='retry'){const retries=[first,second].filter(value=>value.status==='retry');return retries.sort((x,y)=>(x.successes||0)-(y.successes||0))[0]}return first.status==='known'?first:second}
function mergeProgressStates(first,second){if(!first)return second;if(!second)return first;const a=Date.parse(first.savedAt||'')||0,b=Date.parse(second.savedAt||'')||0,newer=b>a?second:first,merged=JSON.parse(JSON.stringify(newer));merged.progress={};const ids=new Set([...Object.keys(first.progress||{}),...Object.keys(second.progress||{})]);for(const id of ids)merged.progress[id]=mergeWordProgress(first.progress?.[id],second.progress?.[id]);merged.sessionNumber=Math.max(first.sessionNumber||0,second.sessionNumber||0);merged.savedAt=new Date(Math.max(a,b,Date.now())).toISOString();return merged}
async function pushCloudState(payload=statePayload()){cloudSavePending=true;try{const result=await api({action:'save-progress',userId:userCode,sessionToken:googleSession,state:payload});if(result?.state?.progress){for(const [id,remoteWord] of Object.entries(result.state.progress))progress[id]=mergeWordProgress(progress[id],remoteWord);const mergedLocal=statePayload();localStorage.setItem(STORAGE_KEY,JSON.stringify(mergedLocal));if(items.length)updateCounts()}cloudSavePending=false;setCloudStatus('ההתקדמות נשמרה בענן · '+Object.keys(progress).length+' מילים עם התקדמות');return result}catch(error){cloudSavePending=false;console.error(error);setCloudStatus('השמירה המקומית פעילה; הענן לא זמין כרגע',true);return null}}
function scheduleCloudSave(payload){clearTimeout(cloudSaveTimer);setCloudStatus('שומר…');cloudSaveTimer=setTimeout(()=>pushCloudState(payload),450)}
function saveState(){const payload=statePayload();localStorage.setItem(STORAGE_KEY,JSON.stringify(payload));if(!localStorage.getItem(STORAGE_KEY))throw new Error('הדפדפן לא שמר את ההתקדמות');scheduleCloudSave(payload)}
function migrateLegacy(){for(const key of LEGACY_KEYS){try{const old=JSON.parse(localStorage.getItem(key)||'null');if(!old)continue;for(const ref of old.known||[]){const id=typeof ref==='string'?ref:ref.id;if(id)progress[id]={status:'known',successes:3,dueSet:null}}for(const ref of old.retry||[]){const id=typeof ref==='string'?ref:ref.id;if(id)progress[id]={status:'retry',successes:0,dueSet:2}}if(typeof old.shuffle==='boolean')shuffleOn=old.shuffle;return}catch{}}}
async function loadState(){let local=null;try{local=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch(error){console.error(error)}try{const query=googleSession?`session=${encodeURIComponent(googleSession)}`:`user=${encodeURIComponent(userCode)}`;const response=await fetch(`${API_URL}?action=progress&${query}`,{cache:'no-store'});const cloud=await response.json();if(!response.ok)throw new Error(cloud.error||'Cloud load failed');const remote=cloud.found?cloud.state:null;if(googleSession){const merged=mergeProgressStates(remote,local);if(merged){applySavedState(merged);localStorage.setItem(STORAGE_KEY,JSON.stringify(merged));await pushCloudState(merged);setCloudStatus((remote?'ההתקדמות סונכרנה מהענן':'ההתקדמות הועלתה לענן')+' · '+Object.keys(progress).length+' מילים עם התקדמות');return}migrateLegacy();if(Object.keys(progress).length)saveState();else setCloudStatus('השמירה בענן מוכנה · אין עדיין התקדמות');return}if(remote&&(!local||String(remote.savedAt||'')>=String(local.savedAt||''))){applySavedState(remote);localStorage.setItem(STORAGE_KEY,JSON.stringify(remote));setCloudStatus('ההתקדמות נטענה מהענן · '+Object.keys(progress).length+' מילים עם התקדמות');return}if(local){applySavedState(local);await pushCloudState(local);return}migrateLegacy();if(Object.keys(progress).length)saveState();else setCloudStatus('השמירה בענן מוכנה · אין עדיין התקדמות')}catch(error){console.error(error);if(local)applySavedState(local);else migrateLegacy();setCloudStatus('הענן לא זמין; נטענה שמירה מקומית',true)}}
function stateOf(q){return progress[itemKey(q)]?.status||'unseen'}
function getStats(list=items){return{all:list.length,known:list.filter(q=>stateOf(q)==='known').length,unseen:list.filter(q=>stateOf(q)==='unseen').length,retry:list.filter(q=>stateOf(q)==='retry').length}}
function setRing(id,count,total,color){const ring=by(id);ring.style.setProperty('--p',total?Math.round(count/total*100):0);ring.style.setProperty('--ring',color)}
function lessonItems(key=selectedLesson){return key==='all'?items:items.filter(q=>q.lesson===key)}
function lessonTitle(key=selectedLesson){return key==='all'?'כל המילים':lessons.find(l=>l.sheet===key)?.title||key}
function updateCounts(){const all=getStats(),scope=getStats(lessonItems());by('totalCount').textContent=all.all;by('knownCount').textContent=all.known;by('unseenCount').textContent=all.unseen;by('retryCount').textContent=all.retry;by('homeAllCount').textContent=scope.all;by('homeUnseenCount').textContent=scope.unseen;by('homeRetryCount').textContent=scope.retry;setRing('allRing',scope.known,scope.all,'#14bd78');setRing('unseenRing',scope.unseen,scope.all,'#ffb800');setRing('retryRing',scope.retry,scope.all,'#ff452f')}

function renderLessonList(){by('lessonList').innerHTML=lessons.map(lesson=>{const list=lessonItems(lesson.sheet),s=getStats(list),knownPct=s.all?Math.round(s.known/s.all*100):0,retryPct=s.all?Math.round(s.retry/s.all*100):0;return '<button class="lesson-card" type="button" data-lesson="'+escapeHtml(lesson.sheet)+'"><span class="lesson-copy"><strong>'+escapeHtml(lesson.title)+'</strong><span class="lesson-progress"><i class="known" style="width:'+knownPct+'%"></i><i class="retry" style="width:'+retryPct+'%"></i></span><span class="lesson-meta"><span>'+s.all+' מילים</span><span>'+s.retry+' לחזרה</span><span>'+knownPct+'% מילים ידועות</span></span></span><span class="lesson-arrow">‹</span></button>'}).join('');by('lessonList').querySelectorAll('[data-lesson]').forEach(button=>button.addEventListener('click',()=>showLesson(button.dataset.lesson)))}
function renderFeatured(){stopAudio();const pool=lessonItems();if(!pool.length)return;if(featuredIndex===null||featuredIndex>=pool.length)featuredIndex=Math.floor(Math.random()*pool.length);const q=pool[featuredIndex];by('featuredWord').textContent=q.w;by('featuredTranslit').textContent='('+q.tr+')';by('featuredMeaning').textContent=q.m.join(' / ');renderMetaTags(by('featuredMeta'),q.f);by('featuredSentence').innerHTML=q.s?highlightWord(q):'למילה הזאת עדיין לא נוסף משפט לדוגמה בגיליון.';setAudioButton(q,'featured')}
function renderHome(){renderLessonList();updateCounts()}
function changeFeatured(delta){const pool=lessonItems();if(activeView!=='lesson'||featuredTransitioning||pool.length<2)return;featuredTransitioning=true;const card=by('featuredCard'),outClass=delta>0?'swipe-out-next':'swipe-out-previous',inClass=delta>0?'swipe-in-next':'swipe-in-previous';card.classList.add(outClass);setTimeout(()=>{card.classList.remove(outClass);featuredIndex=(featuredIndex+delta+pool.length)%pool.length;renderFeatured();card.classList.add(inClass);setTimeout(()=>{card.classList.remove(inClass);featuredTransitioning=false},300)},280)}
function animatePageBack(navigate){if(pageTransitioning)return;pageTransitioning=true;const wrap=document.querySelector('.wrap');wrap.classList.add('page-back-out');setTimeout(()=>{wrap.classList.remove('page-back-out');navigate();wrap.classList.add('page-back-in');setTimeout(()=>{wrap.classList.remove('page-back-in');pageTransitioning=false},300)},240)}
function resetFeaturedCard(card){card.classList.remove('dragging','drag-dismiss');card.style.transition='';card.style.transform='';card.style.opacity=''}
function finishFeaturedDrag(dx){const card=by('featuredCard'),pool=lessonItems();if(!pool.length){resetFeaturedCard(card);featuredTransitioning=false;return}featuredTransitioning=true;card.classList.remove('dragging');card.classList.add('drag-dismiss');card.style.transition='transform .22s ease-in,opacity .22s ease-in';card.style.transform=`translateX(${dx<0?'-125%':'125%'}) rotate(${dx<0?-5:5}deg)`;card.style.opacity='0';setTimeout(()=>{featuredIndex=(featuredIndex+(dx<0?1:-1)+pool.length)%pool.length;renderFeatured();card.style.transition='none';card.style.transform=`translateX(${dx<0?'75px':'-75px'})`;card.style.opacity='0';requestAnimationFrame(()=>requestAnimationFrame(()=>{card.style.transition='transform .28s ease-out,opacity .28s ease-out';card.style.transform='translateX(0)';card.style.opacity='1';setTimeout(()=>{resetFeaturedCard(card);featuredTransitioning=false},290)}))},220)}
function cancelFeaturedDrag(){const card=by('featuredCard');card.classList.remove('dragging');card.style.transition='transform .22s ease-out,opacity .22s ease-out';card.style.transform='translateX(0) rotate(0)';card.style.opacity='1';setTimeout(()=>resetFeaturedCard(card),230)}
function hidePages(){by('settingsButton').hidden=true;by('listBack').hidden=true;by('homePage').hidden=true;by('lessonPage').hidden=true;by('quizPage').hidden=true;by('summaryPage').hidden=true;by('listPage').hidden=true}
function showHome(){closeAllDrawers();activeView='home';by('headerHomeButton').hidden=true;hidePages();by('settingsButton').hidden=false;by('homePage').hidden=false;renderHome()}
function showLesson(key=selectedLesson){closeAllDrawers();selectedLesson=key;featuredIndex=null;activeView='lesson';by('headerHomeButton').hidden=false;by('settingsButton').hidden=true;hidePages();by('lessonPage').hidden=false;by('lessonTitle').textContent=lessonTitle();by('practiceButton').textContent=selectedLesson==='all'?'תרגול מכל המילים':'תרגול השיעור';updateCounts();renderFeatured();saveState()}

function buildSession(filter=sessionFilter){sessionNumber++;sessionResults={};index=0;furthestIndex=0;sessionLesson=selectedLesson;sessionFilter=filter||'all';const tag=sessionFilter.startsWith('tag:')?sessionFilter.slice(4):'',fullPool=tag?items:lessonItems(sessionLesson),pool=tag?fullPool.filter(q=>metaValues(q.f).includes(tag)):sessionFilter==='all'?fullPool:fullPool.filter(q=>stateOf(q)===sessionFilter);if(!pool.length){sessionNumber--;alert('אין כרגע מילים ברשימה הזאת לתרגול.');return}if(sessionFilter==='all'){const eligible=pool.filter(q=>{const p=progress[itemKey(q)];return p?.status==='retry'&&(p.dueSet||0)<=sessionNumber}),reviewTarget=Math.min(eligible.length,2+Math.floor(Math.random()*3)),reviews=shuffled(eligible).slice(0,reviewTarget),used=new Set(reviews.map(itemKey)),unseen=shuffled(pool.filter(q=>stateOf(q)==='unseen'&&!used.has(itemKey(q)))),known=shuffled(pool.filter(q=>stateOf(q)==='known'&&!used.has(itemKey(q)))),waiting=shuffled(pool.filter(q=>stateOf(q)==='retry'&&!used.has(itemKey(q))));order=[...reviews,...unseen,...known,...waiting].slice(0,10)}else order=shuffled(pool).slice(0,10);if(shuffleOn)order=shuffled(order);saveState();showQuiz();draw()}
function currentResult(){return sessionResults[itemKey(order[index])]}
function highlightWord(q){if(!q.s)return'';const marks='[\\u064B-\\u065F\\u0670]*',escape=c=>c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+marks,words=q.w.trim().split(/\s+/).map(word=>word.replace(/[\u064B-\u065F\u0670]/g,'')),parts=words.map(word=>'(?:[وبفكل]?'+marks+'ا?ل'+marks+')?'+[...word].map(escape).join('')),token=parts.join('\\s+'),safeSentence=escapeHtml(q.s);return safeSentence.replace(new RegExp(token,'u'),m=>'<span class="target">'+m+'</span>')}
function highlightHebrew(q){if(!q.t)return'';let stem=q.m.find(m=>q.t.includes(m))||q.m.map(m=>m.replace(/ים$/,'')).find(m=>q.t.includes(m))||q.m[0];const safe=stem.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),safeTranslation=escapeHtml(q.t);return safeTranslation.replace(new RegExp('[א-ת״׳]*'+safe+'[א-ת״׳]*','u'),m=>'<span class="target">'+m+'</span>')}

function renderSessionProgress(){const progressEl=by('sessionProgress'),segments=order.map((q,i)=>{const r=sessionResults[itemKey(q)],classes=[];if(r?.status)classes.push(r.status);if(i===furthestIndex&&!r)classes.push('frontier');if(i===index)classes.push('current');return '<span class="progress-item">'+(i===index?'<b id="counter" class="progress-counter">'+(index+1)+'/'+order.length+'</b>':'')+'<i class="progress-segment '+classes.join(' ')+'"></i></span>'}).join('');progressEl.innerHTML=segments}
function draw(){stopAudio();const q=order[index];if(!q)return;setAudioButton(q,'quiz');const result=currentResult();renderSessionProgress();by('arabicWord').textContent=q.w;by('wordTranslit').textContent='('+q.tr+')';renderMetaTags(by('meta'),q.f);by('arabicSentence').innerHTML=q.s?highlightWord(q):'למילה הזאת עדיין לא נוסף משפט לדוגמה בגיליון.';by('previousButton').disabled=index===0;by('word').value=result?.answer||'';if(result){form.hidden=true;renderFeedback(q,result)}else{const button=by('checkButton');form.hidden=false;feedback.hidden=true;button.disabled=false;button.classList.remove('is-loading');button.removeAttribute('aria-busy');button.textContent='בדיקה'}by('nextButton').textContent=result?(index===order.length-1?'סיום הסט':'מילה הבאה'):(index===order.length-1?'דילוג וסיום':'דילוג');updateCounts()}
function renderFeedback(q,result){const ok=result.status==='correct';feedback.hidden=false;const hasAnswer=!ok&&Boolean(String(result.answer||'').trim());by('wrongAnswerBox').hidden=!hasAnswer;if(hasAnswer)by('mine').textContent=result.answer;by('correct').textContent=ok?q.m.join(' / '):(result.correction||q.m.join(' / '));by('correctSentence').innerHTML=q.t?highlightHebrew(q):'למשפט הזה עדיין לא נוסף תרגום בגיליון.';by('retryNotice').hidden=ok}
function applyOutcome(q,status,answer,details={}){const id=itemKey(q),wasRetry=progress[id]?.status==='retry',updatedAt=new Date().toISOString();if(status==='correct'){const successes=Math.min(3,(progress[id]?.successes||0)+1);if(successes>=3)progress[id]={status:'known',successes:3,dueSet:null,updatedAt};else progress[id]={status:'retry',successes,dueSet:sessionNumber+(successes===1?3:6),updatedAt}}else progress[id]={status:'retry',successes:0,dueSet:sessionNumber+2,updatedAt};sessionResults[id]={status,answer:answer||'',correction:details.correction||q.m.join(' / '),wasRetry};saveState();draw()}

function celebrateAndAdvance(){if(transitioning)return;transitioning=true;const card=by('wordCard'),pop=by('successPop');card.classList.add('transitioning');pop.hidden=false;setTimeout(()=>card.classList.add('swipe-out'),520);setTimeout(()=>{pop.hidden=true;card.classList.remove('swipe-out');if(index===order.length-1){card.classList.remove('transitioning');transitioning=false;showSummary();return}index++;furthestIndex=Math.max(furthestIndex,index);saveState();draw();card.classList.add('swipe-in');requestAnimationFrame(()=>setTimeout(()=>{card.classList.remove('swipe-in','transitioning');transitioning=false},350))},900)}

form.addEventListener('submit',async e=>{e.preventDefault();const q=order[index],answer=by('word').value.trim(),button=by('checkButton');button.disabled=true;button.classList.add('is-loading');button.setAttribute('aria-busy','true');button.innerHTML='בודק<span class="loading-dots" aria-hidden="true"><i></i><i></i><i></i></span>';if(!answer){applyOutcome(q,'wrong','',{correction:q.m.join(' / ')});return}if(matchesLocally(answer,q.m)){applyOutcome(q,'correct',answer);celebrateAndAdvance();return}try{const result=await api({action:'evaluate',word:q.w,acceptedMeanings:q.m,answer});applyOutcome(q,result.correct?'correct':'wrong',answer,result);if(result.correct)celebrateAndAdvance()}catch(error){console.error(error);applyOutcome(q,'wrong',answer,{correction:q.m.join(' / ')})}});
function animateNavigation(direction,changeWord){if(transitioning)return;transitioning=true;const card=by('wordCard'),outClass=direction==='next'?'swipe-out-next':'swipe-out-previous',inClass=direction==='next'?'swipe-in-next':'swipe-in-previous';card.classList.add('transitioning',outClass);setTimeout(()=>{card.classList.remove(outClass);const staysOnQuiz=changeWord();if(staysOnQuiz===false){card.classList.remove('transitioning');transitioning=false;return}draw();card.classList.add(inClass);setTimeout(()=>{card.classList.remove(inClass,'transitioning');transitioning=false},300)},280)}
function nextWord(){if(transitioning)return;const q=order[index];if(!currentResult())applyOutcome(q,'skipped','');animateNavigation('next',()=>{if(index===order.length-1){showSummary();return false}index++;furthestIndex=Math.max(furthestIndex,index);saveState();return true})}
function previousWord(){if(index===0||transitioning)return;animateNavigation('previous',()=>{index--;saveState();return true})}
function navigateOpened(delta){const target=index+delta;if(transitioning||target<0||target>furthestIndex||target>=order.length)return;animateNavigation(delta>0?'next':'previous',()=>{index=target;saveState();return true})}

function showSummary(){saveState();activeView='summary';by('headerHomeButton').hidden=false;hidePages();by('summaryPage').hidden=false;const results=order.map(q=>sessionResults[itemKey(q)]||{status:'skipped'}),correct=results.filter(r=>r.status==='correct').length;by('summaryStats').textContent=correct+' תשובות נכונות מתוך '+order.length;by('summaryList').innerHTML=order.map(q=>{const r=sessionResults[itemKey(q)]||{status:'skipped'},icon=r.status==='correct'?'✅':r.status==='skipped'?'⏭':'❌',arabic=q.s?'<div class="list-sentence">'+highlightWord(q)+'</div>':'',hebrew=q.t?'<div class="summary-translation muted">'+highlightHebrew(q)+'</div>':'';return '<div class="summary-row"><div><div class="list-line"><span class="list-word">'+escapeHtml(q.w)+'</span><span class="muted">('+escapeHtml(q.tr)+') — '+q.m.map(escapeHtml).join(' / ')+'</span></div><div class="muted" style="font-size:13px;margin-top:4px">'+escapeHtml(q.f)+'</div>'+arabic+hebrew+'</div><div><span class="result-icon">'+icon+'</span></div></div>'}).join('')}
function showQuiz(){activeView='quiz';by('headerHomeButton').hidden=false;by('settingsButton').hidden=true;hidePages();by('quizPage').hidden=false}

function clearDrawerDragStyles(){const drawer=by('drawer'),overlay=by('drawerOverlay');drawer.classList.remove('dragging');drawer.style.transition='';drawer.style.transform='';overlay.style.transition='';overlay.style.opacity=''}
function lockPageForMenu(){if(document.body.classList.contains('menu-open'))return;menuScrollY=window.scrollY;document.body.style.top=`-${menuScrollY}px`;document.body.classList.add('menu-open')}
function unlockPageFromMenu(){if(!document.body.classList.contains('menu-open'))return;document.body.classList.remove('menu-open');document.body.style.top='';window.scrollTo(0,menuScrollY)}
function openMenu(){clearTimeout(drawerCloseTimer);clearDrawerDragStyles();updateCounts();const drawer=by('drawer'),overlay=by('drawerOverlay');drawer.scrollTop=0;lockPageForMenu();drawer.hidden=false;overlay.hidden=false;requestAnimationFrame(()=>{drawer.scrollTop=0;drawer.classList.add('is-open');overlay.classList.add('is-open')})}
function closeMenu(){const drawer=by('drawer'),overlay=by('drawerOverlay');if(drawer.hidden)return;clearDrawerDragStyles();drawer.classList.remove('is-open');overlay.classList.remove('is-open');clearTimeout(drawerCloseTimer);drawerCloseTimer=setTimeout(()=>{drawer.hidden=true;overlay.hidden=true;clearDrawerDragStyles();unlockPageFromMenu()},310)}
function openSettings(){clearTimeout(drawerCloseTimer);const drawer=by('settingsDrawer'),overlay=by('drawerOverlay');drawer.scrollTop=0;lockPageForMenu();drawer.hidden=false;overlay.hidden=false;requestAnimationFrame(()=>{drawer.scrollTop=0;drawer.classList.add('is-open');overlay.classList.add('is-open')})}
function closeSettings(){const drawer=by('settingsDrawer'),overlay=by('drawerOverlay');if(drawer.hidden)return;drawer.classList.remove('is-open');overlay.classList.remove('is-open');clearTimeout(drawerCloseTimer);drawerCloseTimer=setTimeout(()=>{drawer.hidden=true;overlay.hidden=true;unlockPageFromMenu()},310)}
function closeAllDrawers(){if(!by('drawer').hidden)closeMenu();else if(!by('settingsDrawer').hidden)closeSettings()}
function cancelDrawerSwipe(){const drawer=by('drawer'),overlay=by('drawerOverlay');drawer.classList.remove('dragging');drawer.style.transition='transform .22s ease-out';drawer.style.transform='translateX(0)';overlay.style.transition='opacity .22s ease-out';overlay.style.opacity='1';setTimeout(clearDrawerDragStyles,230)}
function finishDrawerSwipe(){const drawer=by('drawer'),overlay=by('drawerOverlay');drawer.classList.remove('dragging','is-open');overlay.classList.remove('is-open');drawer.style.transition='transform .24s ease-in';drawer.style.transform='translateX(105%)';overlay.style.transition='opacity .2s ease';overlay.style.opacity='0';clearTimeout(drawerCloseTimer);drawerCloseTimer=setTimeout(()=>{drawer.hidden=true;overlay.hidden=true;clearDrawerDragStyles();unlockPageFromMenu()},250)}
function showList(type){listReturnView=activeView==='list'?listReturnView:activeView;activeView='list';activeListType=type;closeMenu();by('headerHomeButton').hidden=true;const tag=type.startsWith('tag:')?type.slice(4):'',pool=tag?items:lessonItems(),list=tag?pool.filter(q=>metaValues(q.f).includes(tag)):type==='all'?pool:pool.filter(q=>stateOf(q)===type),titles={all:'כל המילים',known:'מילים שאני יודע',unseen:'עוד לא למדתי',retry:'מילים לחזרה'};by('listTitle').textContent=(tag?tag:titles[type]+(selectedLesson==='all'?'':' · '+lessonTitle()))+' ('+list.length+')';by('listPractice').hidden=!list.length;by('listPractice').textContent=type==='retry'?'תרגול המילים לחזרה':'תרגול הרשימה';by('wordList').innerHTML=list.length?list.map(q=>{const key=escapeHtml(itemKey(q));return '<div class="word-row"><div class="list-row-content"><div class="list-line"><span class="list-word">'+escapeHtml(q.w)+'</span><span class="muted">('+escapeHtml(q.tr)+') — '+q.m.map(escapeHtml).join(' / ')+'</span></div>'+metaTagsHtml(q.f)+(q.s?'<div class="list-sentence">'+highlightWord(q)+'</div><div class="muted" style="font-size:15px;margin-top:5px">'+highlightHebrew(q)+'</div>':'')+'</div><button class="audio-button list-audio" type="button" data-audio-id="'+key+'" title="השמעת המילה והמשפט" aria-label="השמעת המילה ואז המשפט"></button></div>'}).join(''):'<div class="empty">הרשימה עדיין ריקה</div>';by('wordList').querySelectorAll('.list-audio').forEach(restoreAudioIcon);hidePages();by('listBack').hidden=false;by('listPage').hidden=false}
async function resetAll(){if(!confirm('למחוק את כל ההתקדמות מהמכשיר ומהענן? המילים עצמן לא יימחקו.'))return;clearTimeout(cloudSaveTimer);progress={};sessionResults={};order=[];index=0;furthestIndex=0;sessionNumber=0;selectedLesson='all';sessionLesson='all';localStorage.removeItem(STORAGE_KEY);for(const key of LEGACY_KEYS)localStorage.removeItem(key);try{await api({action:'reset-progress',userId:userCode,sessionToken:googleSession});setCloudStatus('ההתקדמות אופסה')}catch(error){console.error(error);setCloudStatus('האיפוס בענן לא הושלם',true)}featuredIndex=null;showHome()}

function loadGoogleAccount(){googleSession=localStorage.getItem(GOOGLE_SESSION_KEY)||'';try{googleProfile=JSON.parse(localStorage.getItem(GOOGLE_PROFILE_KEY)||'null')}catch{googleProfile=null}}
function renderGoogleAccount(){const signedIn=Boolean(googleSession&&googleProfile);by('googleProfile').hidden=!signedIn;by('googleSignOut').hidden=!signedIn;by('googleSignIn').hidden=signedIn;if(signedIn){by('googleName').textContent=googleProfile.name||'משתמש Google';by('googleEmail').textContent=googleProfile.email||'';by('googlePicture').src=googleProfile.picture||'';by('googlePicture').hidden=!googleProfile.picture}}
async function handleGoogleCredential(response){if(!response?.credential)return;setCloudStatus('מתחבר לחשבון Google…');try{clearTimeout(cloudSaveTimer);await pushCloudState(statePayload());const result=await api({action:'google-login',credential:response.credential,anonymousUserId:userCode});googleSession=result.sessionToken;googleProfile=result.profile;localStorage.setItem(GOOGLE_SESSION_KEY,googleSession);localStorage.setItem(GOOGLE_PROFILE_KEY,JSON.stringify(googleProfile));setCloudStatus('חשבון Google חובר בהצלחה');location.reload()}catch(error){console.error(error);setCloudStatus('החיבור ל־Google נכשל. אפשר לנסות שוב.',true)}}
function initGoogleSignIn(){renderGoogleAccount();if(googleSession)return;let attempts=0;const ready=setInterval(()=>{attempts++;if(window.google?.accounts?.id){clearInterval(ready);google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:handleGoogleCredential});google.accounts.id.renderButton(by('googleSignIn'),{type:'standard',theme:'outline',size:'large',text:'signin_with',shape:'rectangular',width:280,locale:'he'})}else if(attempts>40){clearInterval(ready);setCloudStatus('לא הצלחנו לטעון את כפתור Google',true)}},150)}
async function signOutGoogle(){if(!confirm('להתנתק מחשבון Google במכשיר הזה? ההתקדמות תישאר שמורה בענן.'))return;localStorage.removeItem(GOOGLE_SESSION_KEY);localStorage.removeItem(GOOGLE_PROFILE_KEY);googleSession='';googleProfile=null;if(window.google?.accounts?.id)google.accounts.id.disableAutoSelect();location.reload()}

by('featuredAudio').addEventListener('click',e=>{e.stopPropagation();playWordAndSentence(lessonItems()[featuredIndex],e.currentTarget)});by('quizAudio').addEventListener('click',e=>{e.stopPropagation();playWordAndSentence(order[index],e.currentTarget)});
document.querySelectorAll('.meta-tags').forEach(container=>container.addEventListener('click',e=>{const tagButton=e.target.closest('[data-tag]');if(!tagButton)return;e.preventDefault();e.stopPropagation();tagButton.classList.add('is-pressed');setTimeout(()=>tagButton.classList.remove('is-pressed'),160);showList('tag:'+tagButton.dataset.tag)}));
by('wordList').addEventListener('click',e=>{const audioButton=e.target.closest('[data-audio-id]');if(audioButton){const q=items.find(item=>itemKey(item)===audioButton.dataset.audioId);if(q)playWordAndSentence(q,audioButton);return}const tagButton=e.target.closest('[data-tag]');if(!tagButton)return;e.preventDefault();tagButton.classList.add('is-pressed');setTimeout(()=>tagButton.classList.remove('is-pressed'),160);showList('tag:'+tagButton.dataset.tag)});
by('checkButton').addEventListener('pointerdown',e=>{e.preventDefault();if(!by('checkButton').disabled)form.requestSubmit()});by('checkButton').addEventListener('click',()=>{if(!by('checkButton').disabled)form.requestSubmit()});by('nextButton').addEventListener('click',nextWord);by('previousButton').addEventListener('click',previousWord);by('continueButton').addEventListener('click',()=>buildSession(sessionFilter));by('practiceButton').addEventListener('click',()=>{if(order.length&&sessionLesson===selectedLesson&&sessionFilter==='all'&&Object.keys(sessionResults).length<order.length){showQuiz();draw()}else buildSession('all')});by('listPractice').addEventListener('click',()=>buildSession(activeListType));by('allLessonsButton').addEventListener('click',()=>showLesson('all'));by('homeButton').addEventListener('click',showHome);by('menuButton').addEventListener('click',openMenu);by('closeMenu').addEventListener('click',closeMenu);by('drawerOverlay').addEventListener('click',closeMenu);by('resetProgress').addEventListener('click',resetAll);by('listBack').addEventListener('click',()=>animatePageBack(()=>{if(listReturnView==='home')showHome();else if(listReturnView==='lesson')showLesson();else if(listReturnView==='summary')showSummary();else{showQuiz();draw()}}));document.querySelectorAll('[data-list]').forEach(b=>b.addEventListener('click',()=>{selectedLesson='all';showList(b.dataset.list)}));document.querySelectorAll('[data-home-list]').forEach(b=>b.addEventListener('click',()=>showList(b.dataset.homeList)));by('shuffleButton').addEventListener('click',()=>{shuffleOn=!shuffleOn;by('shuffleButton').classList.toggle('active',shuffleOn);by('shuffleButton').querySelector('.menu-icon').textContent=shuffleOn?'🔀':'⇥';saveState()});by('word').addEventListener('focus',()=>{if(window.innerWidth<=560)setTimeout(()=>by('wordCard').scrollIntoView({behavior:'smooth',block:'start'}),280)});

by('drawer').addEventListener('pointerdown',e=>{if(!e.isPrimary||e.target.closest('input,a'))return;drawerPointerStart={x:e.clientX,y:e.clientY,dx:0,pointerId:e.pointerId,dragging:false,cancelled:false};try{by('drawer').setPointerCapture(e.pointerId)}catch{}});
by('drawer').addEventListener('pointermove',e=>{const drag=drawerPointerStart;if(!drag||drag.pointerId!==e.pointerId||drag.cancelled)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.dx=Math.max(0,dx);if(!drag.dragging){if(Math.abs(dx)<7&&Math.abs(dy)<7)return;if(Math.abs(dy)>Math.abs(dx)||dx<0){drag.cancelled=true;return}drag.dragging=true;by('drawer').classList.add('dragging')}if(drag.dragging){e.preventDefault();e.stopPropagation();const drawer=by('drawer'),ratio=Math.min(1,drag.dx/drawer.offsetWidth);drawer.style.transform=`translateX(${drag.dx}px)`;by('drawerOverlay').style.opacity=String(1-ratio*.8)}});
by('drawer').addEventListener('pointerup',e=>{const drag=drawerPointerStart;if(!drag||drag.pointerId!==e.pointerId)return;drawerPointerStart=null;try{by('drawer').releasePointerCapture(e.pointerId)}catch{}if(!drag.dragging){clearDrawerDragStyles();return}by('drawer').dataset.suppressClick='1';setTimeout(()=>{delete by('drawer').dataset.suppressClick},350);e.preventDefault();e.stopPropagation();if(drag.dx>Math.min(100,by('drawer').offsetWidth*.24))finishDrawerSwipe();else cancelDrawerSwipe()});
by('drawer').addEventListener('pointercancel',()=>{const wasDragging=drawerPointerStart?.dragging;drawerPointerStart=null;if(wasDragging)cancelDrawerSwipe();else clearDrawerDragStyles()});
by('drawer').addEventListener('click',e=>{if(by('drawer').dataset.suppressClick==='1'){e.preventDefault();e.stopImmediatePropagation();delete by('drawer').dataset.suppressClick}},true);

by('featuredCard').addEventListener('pointerdown',e=>{if(!e.isPrimary||featuredTransitioning||e.target.closest('button'))return;featurePointerStart={x:e.clientX,y:e.clientY,dx:0,pointerId:e.pointerId,dragging:false,cancelled:false};try{by('featuredCard').setPointerCapture(e.pointerId)}catch{}});
by('featuredCard').addEventListener('pointermove',e=>{const drag=featurePointerStart;if(!drag||drag.pointerId!==e.pointerId||drag.cancelled)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.dx=dx;if(!drag.dragging){if(Math.abs(dx)<7&&Math.abs(dy)<7)return;if(Math.abs(dy)>Math.abs(dx)){drag.cancelled=true;return}drag.dragging=true;by('featuredCard').classList.add('dragging')}if(drag.dragging){e.preventDefault();e.stopPropagation();const card=by('featuredCard'),rotation=Math.max(-5,Math.min(5,dx/28));card.style.transform=`translateX(${dx}px) rotate(${rotation}deg)`;card.style.opacity=String(Math.max(.55,1-Math.abs(dx)/(card.offsetWidth*1.8)))}});
by('featuredCard').addEventListener('pointerup',e=>{const drag=featurePointerStart;if(!drag||drag.pointerId!==e.pointerId)return;featurePointerStart=null;try{by('featuredCard').releasePointerCapture(e.pointerId)}catch{}if(!drag.dragging){resetFeaturedCard(by('featuredCard'));return}e.preventDefault();e.stopPropagation();const threshold=Math.min(105,by('featuredCard').offsetWidth*.22);if(Math.abs(drag.dx)>=threshold)finishFeaturedDrag(drag.dx);else cancelFeaturedDrag()});
by('featuredCard').addEventListener('pointercancel',()=>{const wasDragging=featurePointerStart?.dragging;featurePointerStart=null;if(wasDragging)cancelFeaturedDrag();else resetFeaturedCard(by('featuredCard'))});
by('featuredCard').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();changeFeatured(1)}else if(e.key==='ArrowRight'){e.preventDefault();changeFeatured(-1)}});
by('wordCard').addEventListener('pointerdown',e=>{if(!e.isPrimary||e.target.closest('input,button,form'))return;wordPointerStart={x:e.clientX,y:e.clientY}});
by('wordCard').addEventListener('pointerup',e=>{if(!wordPointerStart)return;const dx=e.clientX-wordPointerStart.x,dy=e.clientY-wordPointerStart.y;wordPointerStart=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.25)navigateOpened(dx<0?1:-1)});
by('wordCard').addEventListener('pointercancel',()=>{wordPointerStart=null});
by('word').addEventListener('focus',()=>{if(window.innerWidth<=560)setTimeout(()=>by('keyboardSpacer').scrollIntoView({behavior:'smooth',block:'end'}),420)});
by('headerHomeButton').addEventListener('click',()=>animatePageBack(showHome));
by('copyUserCode').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(userCode);setCloudStatus('קוד השחזור הועתק')}catch{prompt('העתק את קוד השחזור:',userCode)}});
by('restoreUserCode').addEventListener('click',()=>{const code=(prompt('הדבק את קוד השחזור שלך:')||'').trim().toLowerCase();if(!code)return;if(!/^[a-f0-9]{32}$/.test(code)){alert('קוד השחזור אינו תקין');return}if(code===userCode)return;if(!confirm('לטעון את ההתקדמות המשויכת לקוד הזה?'))return;localStorage.setItem(USER_CODE_KEY,code);localStorage.removeItem(STORAGE_KEY);location.reload()});
by('googleSignOut').addEventListener('click',signOutGoogle);
by('settingsButton').addEventListener('click',openSettings);
by('closeSettings').addEventListener('click',closeSettings);
by('drawerOverlay').addEventListener('click',closeSettings);

if('serviceWorker' in navigator)window.addEventListener('load',()=>{let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});navigator.serviceWorker.register('./service-worker.js').then(registration=>registration.update()).catch(error=>console.warn('Service worker registration failed',error))});
(async()=>{try{userCode=getUserCode();loadGoogleAccount();by('userCode').textContent=userCode;initGoogleSignIn();const vocabularyLoad=await loadVocabulary();await loadState();if(vocabularyLoad.cached)setCloudStatus('אין חיבור כרגע; נטען אוצר המילים האחרון שנשמר',true);by('shuffleButton').classList.toggle('active',shuffleOn);by('shuffleButton').querySelector('.menu-icon').textContent=shuffleOn?'🔀':'⇥';showHome()}catch(error){console.error(error);by('featuredSentence').textContent='לא הצלחנו לטעון את אוצר המילים: '+error.message}})();
